### 주최자가 채팅방 개설
POST http://localhost:8080/api/chatroom?gatheringId=3
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwicm9sZXMiOlsiUk9MRV9NRU1CRVIiXSwiaWF0IjoxNzE2Mzc4OTQzLCJleHAiOjE3MTY0NjUzNDN9.RJHzqGUP-TCCEBDoK8D4mlnrLhPBH1PVplO1-ZwStOU

### 승인된 멤버가 채팅방 참여
PUT http://localhost:8080/api/chatroom/join?chatroomId=3&participationId=8
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIzIiwicm9sZXMiOlsiUk9MRV9NRU1CRVIiXSwiaWF0IjoxNzE2NTU1MDMyLCJleHAiOjE3MTY2NDE0MzJ9.uECvUWizDCBMQc9klSTA_zfHAJO2Z4ThDqp7iyTWWbM

### 채팅에 참여중인 멤버가 채팅방 나가기
PUT http://localhost:8080/api/chatroom/leave?chatroomId=3&participationId=8
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIzIiwicm9sZXMiOlsiUk9MRV9NRU1CRVIiXSwiaWF0IjoxNzE2NTU1MDMyLCJleHAiOjE3MTY2NDE0MzJ9.uECvUWizDCBMQc9klSTA_zfHAJO2Z4ThDqp7iyTWWbM

### 내가 참여하고 있는 채팅 목록 조회
GET http://localhost:8080/api/chatroom/my-list
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIzIiwicm9sZXMiOlsiUk9MRV9NRU1CRVIiXSwiaWF0IjoxNzE2NTU1MDMyLCJleHAiOjE3MTY2NDE0MzJ9.uECvUWizDCBMQc9klSTA_zfHAJO2Z4ThDqp7iyTWWbM

###
GET http://localhost:8080/api/chatroom/3/participants
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIzIiwicm9sZXMiOlsiUk9MRV9NRU1CRVIiXSwiaWF0IjoxNzE2NTU1MDMyLCJleHAiOjE3MTY2NDE0MzJ9.uECvUWizDCBMQc9klSTA_zfHAJO2Z4ThDqp7iyTWWbM
